'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KMAB_2._0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        '''  속성을 재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property DefaultIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property error_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
        '''#Fri Jul 31 14:08:05 KST 2015
        '''eula=true
        '''과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property eula() As String
            Get
                Return ResourceManager.GetString("eula", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_JAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_JAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ICON_ZIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ICON_ZIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property MyIcon48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MyIcon48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  #Minecraft server properties
        '''#Sun Feb 99 00:00:00 KST 2016
        '''generator-settings=
        '''op-permission-level=4
        '''allow-nether=true
        '''resource-pack-hash=
        '''level-name=world
        '''enable-query=false
        '''allow-flight=false
        '''announce-player-achievements=true
        '''server-port=25565
        '''max-world-size=29999984
        '''level-type=DEFAULT
        '''enable-rcon=false
        '''level-seed=
        '''force-gamemode=false
        '''server-ip=
        '''network-compression-threshold=256
        '''max-build-height=256
        '''spawn-npcs=true
        '''white-list=false
        '''spawn-animals=true
        '''snooper-enabled=true
        '''hardcore=f[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property server() As String
            Get
                Return ResourceManager.GetString("server", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  [default]
        '''slot1=Spigot
        '''slot2=Craftbukkit
        '''slot3=MCPC
        '''slot4=Rainbow
        '''slot5=Paperspigot
        '''
        '''[Spigot]
        '''plusdir=false
        '''canmod=false
        '''twoblock=false
        '''ver1=1.4.7\http://tcpr.ca/files/spigot/spigot-1.4.7-R1.1-SNAPSHOT.jar
        '''ver2=1.5.2\http://tcpr.ca/files/spigot/spigot-1.5.2-R1.1-SNAPSHOT.jar
        '''ver3=1.6.2\http://tcpr.ca/files/spigot/spigot-1.6.2-R1.1-SNAPSHOT.jar
        '''ver4=1.6.4\http://tcpr.ca/files/spigot/spigot-1.6.4-R2.1-SNAPSHOT.jar
        '''ver5=1.7.2\http://tcpr.ca/files/spigot/spigot-1.7.2-R0.4-SNAPSHOT-1339.jar
        '''ver6=[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property URLdata() As String
            Get
                Return ResourceManager.GetString("URLdata", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
